### MNIST

In [1]:

from tensorflow.keras.datasets import mnist, fashion_mnist, cifar10
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = mnist.load_data()
num_classes = y_train.max()-y_train.min()+1
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255

y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)
x_train.shape

2025-05-12 13:39:01.806242: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1747046341.834916   30764 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1747046341.841858   30764 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1747046341.858977   30764 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747046341.859010   30764 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747046341.859013   30764 computation_placer.cc:177] computation placer alr

(60000, 28, 28)

### NN 1

In [2]:
num_pixels = x_test.shape[1]*x_test.shape[2]
x_train_resh = x_train.reshape((x_train.shape[0], num_pixels))
x_test_resh = x_test.reshape((x_test.shape[0], num_pixels))
x_train_resh.shape


(60000, 784)

In [4]:
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input, Model

inputs = Input(shape=(x_train_resh.shape[1],))
x = Dense(512, activation="relu")(inputs)
x = Dense(256, activation="relu")(x)
x = Dense(10, activation="softmax")(x)
model0 = Model(inputs=inputs, outputs=x)
model0.summary()

2025-05-12 13:54:35.945824: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

model0.compile(optimizer='adam',loss='categorical_crossentropy',
              metrics=['accuracy','precision','recall'])
model0.fit(x_train_resh, y_train, epochs=20, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model0.evaluate(x_test_resh,y_test)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')

pred = model0.predict(x_test_resh)
y_pred = np.argmax(pred, axis=1)
y_test0 = np.argmax(y_test, axis=1)
print(confusion_matrix(y_test0,y_pred))
print(classification_report(y_test0, y_pred))


Epoch 1/20


2025-05-12 13:55:35.845514: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 141120000 exceeds 10% of free system memory.


352/352 ━━━━━━━━━━━━━━━━━━━━ 10s 21ms/step - accuracy: 0.9891 - loss: 0.0305 - precision: 0.9903 - recall: 0.9887 - val_accuracy: 0.9757 - val_loss: 0.0920 - val_precision: 0.9775 - val_recall: 0.9745
Epoch 2/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9938 - loss: 0.0193 - precision: 0.9945 - recall: 0.9930 - val_accuracy: 0.9761 - val_loss: 0.0925 - val_precision: 0.9779 - val_recall: 0.9748
Epoch 3/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.9947 - loss: 0.0155 - precision: 0.9953 - recall: 0.9943 - val_accuracy: 0.9745 - val_loss: 0.1035 - val_precision: 0.9761 - val_recall: 0.9736
Epoch 4/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9954 - loss: 0.0136 - precision: 0.9958 - recall: 0.9952 - val_accuracy: 0.9760 - val_loss: 0.1047 - val_precision: 0.9770 - val_recall: 0.9751
Epoch 5/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9956 - loss: 0.0122 - precision: 0.9960 - recall: 0.9952 - val_accuracy: 0.9758 - val_loss: 0.1116 

### CNN 1

In [8]:

from tensorflow.keras.layers import Conv2D,MaxPooling2D, Flatten

inputs = Input(shape=(28, 28, 1))
x = Conv2D(filters=32, kernel_size=3, activation="relu")(inputs)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = Flatten()(x)
outputs = Dense(10, activation="softmax")(x)
model = Model(inputs=inputs, outputs=outputs)
model.summary()


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 3, 3, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │        11,530 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,202 (407.04 KB)

 Trainable params: 104,202 (407.04 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:

model.compile(optimizer='adam',loss='categorical_crossentropy',
              metrics=['accuracy','precision','recall'])
model.fit(x_train, y_train, epochs=10, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model.evaluate(x_test,y_test)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')




Epoch 1/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 27s 68ms/step - accuracy: 0.9987 - loss: 0.0036 - precision: 0.9987 - recall: 0.9987 - val_accuracy: 0.9892 - val_loss: 0.0505 - val_precision: 0.9896 - val_recall: 0.9889
Epoch 2/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - accuracy: 0.9991 - loss: 0.0032 - precision: 0.9992 - recall: 0.9991 - val_accuracy: 0.9883 - val_loss: 0.0586 - val_precision: 0.9885 - val_recall: 0.9880
Epoch 3/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - accuracy: 0.9986 - loss: 0.0043 - precision: 0.9986 - recall: 0.9986 - val_accuracy: 0.9896 - val_loss: 0.0516 - val_precision: 0.9899 - val_recall: 0.9895
Epoch 4/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - accuracy: 0.9995 - loss: 0.0021 - precision: 0.9995 - recall: 0.9995 - val_accuracy: 0.9898 - val_loss: 0.0506 - val_precision: 0.9901 - val_recall: 0.9897
Epoch 5/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - accuracy: 0.9995 - loss: 0.0015 - precision: 0.9995 - recall: 0.9995 - val_accuracy: 0.9878 - va

In [26]:
pred = model.predict(x_test)
y_pred = np.argmax(pred, axis=1)
y_test = np.argmax(y_test, axis=1)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step
[[ 975    0    0    0    0    0    1    2    1    1]
 [   0 1132    0    1    0    0    1    1    0    0]
 [   0    0 1022    0    3    0    1    5    1    0]
 [   0    0    2  999    0    5    0    2    2    0]
 [   0    0    0    0  976    0    0    0    0    6]
 [   2    0    0    4    0  884    1    0    0    1]
 [   3    1    1    0    1    1  950    0    1    0]
 [   0    1    1    0    1    0    0 1024    0    1]
 [   1    0    1    0    0    0    1    5  962    4]
 [   0    1    0    0    4   10    1    6    2  985]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       1.00      1.00      1.00      1135
           2       1.00      0.99      0.99      1032
           3       1.00      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.98      0.99      0.99       892
           6       0.99      0.99      0.99      

## FASHION MNIST

In [13]:
(x_train2, y_train2), (x_test2, y_test2) = fashion_mnist.load_data()
num_classes = y_train2.max()-y_train2.min()+1
x_train2 = x_train2.astype("float32") / 255
x_test2 = x_test2.astype("float32") / 255
y_train2 = to_categorical(y_train2, num_classes)
y_test2 = to_categorical(y_test2, num_classes)

### NN 2

In [14]:
num_pixels = x_test2.shape[1]*x_test2.shape[2]
x_train2_resh = x_train2.reshape((x_train2.shape[0], num_pixels))
x_test2_resh = x_test2.reshape((x_test2.shape[0], num_pixels))
x_train2_resh.shape

(60000, 784)

In [17]:
inputs = Input(shape=(x_train2_resh.shape[1],)) 
x = Dense(1024, activation="relu")(inputs)
x = Dense(512, activation="relu")(x)
x = Dense(256, activation="relu")(x)
x = Dense(10, activation="softmax")(x)
model0_2 = Model(inputs=inputs, outputs=x)
model0_2.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1024)           │       803,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,462,538 (5.58 MB)

 Trainable params: 1,462,538 (5.58 MB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model0_2.compile(loss="categorical_crossentropy", optimizer="adam", 
                 metrics=['accuracy','precision','recall'])
model0_2.fit(x_train2_resh, y_train2, epochs=70, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model0_2.evaluate(x_test2_resh,y_test2)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')


Epoch 1/70
352/352 ━━━━━━━━━━━━━━━━━━━━ 17s 39ms/step - accuracy: 0.7582 - loss: 0.6772 - precision: 0.8420 - recall: 0.6775 - val_accuracy: 0.8573 - val_loss: 0.3926 - val_precision: 0.8931 - val_recall: 0.8208
Epoch 2/70
352/352 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.8617 - loss: 0.3743 - precision: 0.8926 - recall: 0.8339 - val_accuracy: 0.8761 - val_loss: 0.3395 - val_precision: 0.8999 - val_recall: 0.8547
Epoch 3/70
352/352 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - accuracy: 0.8821 - loss: 0.3239 - precision: 0.9060 - recall: 0.8586 - val_accuracy: 0.8664 - val_loss: 0.3616 - val_precision: 0.8925 - val_recall: 0.8389
Epoch 4/70
352/352 ━━━━━━━━━━━━━━━━━━━━ 12s 35ms/step - accuracy: 0.8861 - loss: 0.2999 - precision: 0.9078 - recall: 0.8657 - val_accuracy: 0.8778 - val_loss: 0.3414 - val_precision: 0.8979 - val_recall: 0.8611
Epoch 5/70
352/352 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - accuracy: 0.8940 - loss: 0.2823 - precision: 0.9137 - recall: 0.8781 - val_accuracy: 0.8802 - va

In [ ]:
pred2 = model0_2.predict(x_test2_resh)
y_pred2 = np.argmax(pred2, axis=1)
y_test02 = np.argmax(y_test2, axis=1)
print(confusion_matrix(y_test02,y_pred2))
print(classification_report(y_test02, y_pred2))

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step
[[808   2  16  17   5   0 142   0  10   0]
 [  0 986   1   8   2   0   2   0   1   0]
 [ 14   1 817  11  90   0  65   0   2   0]
 [ 12  11  10 900  34   0  28   0   5   0]
 [  0   0  93  29 814   0  60   0   4   0]
 [  0   0   0   1   0 972   0  17   2   8]
 [ 90   2  66  26  61   0 745   0  10   0]
 [  0   0   0   0   0  11   0 970   0  19]
 [  2   0   2   3   1   3   2   3 984   0]
 [  0   0   0   0   0   5   1  35   0 959]]
              precision    recall  f1-score   support

           0       0.87      0.81      0.84      1000
           1       0.98      0.99      0.99      1000
           2       0.81      0.82      0.81      1000
           3       0.90      0.90      0.90      1000
           4       0.81      0.81      0.81      1000
           5       0.98      0.97      0.98      1000
           6       0.71      0.74      0.73      1000
           7       0.95      0.97      0.96      1000
           8       0.97      0.98      0.

### CNN 2

In [21]:
inputs = Input(shape=(28, 28, 1))
x = Conv2D(filters=32, kernel_size=3, activation="relu")(inputs)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = Flatten()(x)
outputs = Dense(10, activation="softmax")(x)
model2 = Model(inputs=inputs, outputs=outputs)
model2.summary()


Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 3, 3, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 10)             │        11,530 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,202 (407.04 KB)

 Trainable params: 104,202 (407.04 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model2 = Model(inputs=inputs, outputs=outputs)
model2.compile(optimizer='adam',loss='categorical_crossentropy',
              metrics=['accuracy','precision','recall'])

model2.fit(x_train2, y_train2, epochs=20, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model2.evaluate(x_test2,y_test2)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')

Epoch 1/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 34s 77ms/step - accuracy: 0.9912 - loss: 0.0239 - precision: 0.9913 - recall: 0.9909 - val_accuracy: 0.9011 - val_loss: 0.5838 - val_precision: 0.9023 - val_recall: 0.9003
Epoch 2/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - accuracy: 0.9909 - loss: 0.0270 - precision: 0.9914 - recall: 0.9908 - val_accuracy: 0.9101 - val_loss: 0.5371 - val_precision: 0.9115 - val_recall: 0.9093
Epoch 3/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - accuracy: 0.9940 - loss: 0.0173 - precision: 0.9941 - recall: 0.9938 - val_accuracy: 0.9091 - val_loss: 0.5411 - val_precision: 0.9100 - val_recall: 0.9081
Epoch 4/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 22s 64ms/step - accuracy: 0.9945 - loss: 0.0159 - precision: 0.9948 - recall: 0.9942 - val_accuracy: 0.9092 - val_loss: 0.5571 - val_precision: 0.9101 - val_recall: 0.9085
Epoch 5/20
352/352 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - accuracy: 0.9943 - loss: 0.0153 - precision: 0.9944 - recall: 0.9942 - val_accuracy: 0.8997 - va

ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 10)

In [ ]:
pred2 = model2.predict(x_test2)
y_pred2 = np.argmax(pred2, axis=1)
y_test2 = np.argmax(y_test2, axis=1)
print(confusion_matrix(y_test2,y_pred2))
print(classification_report(y_test2, y_pred2))

## CIFAR 10

In [ ]:
(x_train3, y_train3), (x_test3, y_test3) = cifar10.load_data()
num_classes = y_train3.max()-y_train3.min()+1
x_train3 = x_train3.astype("float32") / 255
x_test3 = x_test3.astype("float32") / 255
y_train3 = to_categorical(y_train3, num_classes)
y_test3 = to_categorical(y_test3, num_classes)

### NN 3

In [ ]:
inputs = Flatten(input_shape=x_train3.shape[1:])
x = Dense(1024, activation="relu")(input)
x = Dense(512, activation="relu")(x)
x = Dense(512, activation="relu")(x)
x = Dense(256, activation="relu")(x)
outputs = Dense(10, activation="softmax")(x)
model0_3 = Model(input=inputs, outputs=outputs)

In [ ]:
model0_3.compile(loss="categorical_crossentropy", optimizer="adam", 
               metrics=['accuracy','precision','recall'])
model0_3.fit(x_train3, y_train3, epochs=100, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model0_3.evaluate(x_test3,y_test3)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')

In [ ]:
pred3 = model0_3.predict(x_test3)
y_pred3 = np.argmax(pred3, axis=1)
y_test03 = np.argmax(y_test3, axis=1)
print(confusion_matrix(y_test03,y_pred3))
print(classification_report(y_test03, y_pred3))

### CNN 3

In [ ]:
inputs = Input(shape=(32, 32, 1))
x = Conv2D(filters=32, kernel_size=3, activation="relu")(inputs)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = MaxPooling2D(pool_size=2)(x)
x = Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = Flatten()(x)
outputs = Dense(10, activation="softmax")(x)
model3 = Model(inputs=inputs, outputs=outputs)
model3.compile(optimizer='adam',loss='categorical_crossentropy',
              metrics=['accuracy','precision','recall'])

model3.fit(x_train3, y_train3, epochs=20, batch_size=128, validation_split=0.25, verbose=1)
loss, acc, prec, rec = model3.evaluate(x_test3,y_test3)
print(f'accuracy: {acc},\n precision: {prec},\n recall: {rec}')

In [ ]:
pred3 = model3.predict(x_test3)
y_pred3 = np.argmax(pred3, axis=1)
y_test3 = np.argmax(y_test3, axis=1)
print(confusion_matrix(y_test3,y_pred3))
print(classification_report(y_test3, y_pred3))